### ISSUE TITLE
Update README - Global Install

### ISSUE THREAD

**Issue by alistair-hmh** [xojs/eslint-config-xo-react#20]
- **Scenario** - lint using `xo-config-xo-react` in a fresh `create-react-app` project.
- **Problem** - `Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'` 
- **Solution** - Needs global install of `eslint-plugin-react`.

Your current README suggests that the following `package.json` should work:

```json
{
  "name": "react-xo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "1.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "lint": "npx xo",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "eslint-config-xo-react": "^0.17.0",
    "eslint-plugin-react": "^7.11.1"
  },
  "xo": {
    "extends": "xo-react"
  }
}
```

When I...

```shell
npm run lint
```

Node throws:

```shell
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/plugins.js:96:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/plugins.js:157:21)
    at loadFromDisk (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/config-file.js:506:35)
    at load (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/config/config-file.js:408:26)
```

However, when I...

```shell 
npm i -g eslint-plugin-react
```

...then linting works as expected:

```shell
❯ npm run lint

> react-xo@0.1.0 lint /Users/macdonalda/repos/react-xo/react-xo
> npx xo

  src/index.js:3:1
  ✖    3:1   Imported module should be assigned                                       
... REMOVED A TON OF FAILURES TO KEEP THIS SHORT ...
  ✖  116:1   Expected indentation of 1 tab but found 2 spaces.                        indent

  132 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-xo@0.1.0 lint: `npx xo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-xo@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macdonalda/.npm/_logs/2018-09-20T17_42_06_819Z-debug.log
```

I found this suggestion here: https://github.com/eslint/eslint/issues/3782#issuecomment-139849803

Is it worth updating the docs for this?

**Comment by sindresorhus** [comment]
Installing globally is *definitely* not the correct solution. This is most likely a problem with `create-react-app` and how it handles ESLint. Open an issue on `create-react-app`.
